version: '3'
services:
  api1:
    build: ./service1/
    ports:
      - 3000:3000
  api2:
    build: ./service2/
    ports:
      - 3001:3000
  api3:
    build: ./service3/
    ports:
      - 3002:3000
  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes: 
      - "./apigateway/api.conf:/etc/nginx/conf.d/default.conf"